### ISSUE TITLE
建议增加支持Mikan其他类型RSS代理

### ISSUE THREAD

**Issue by LinxHex** [JeffersonQin/mikanani-proxy#3]
目前只能代理个人账号订阅的RSS`https://mikanani.me/Home/MyBangumi`，
搜索结果RSS`https://mikanani.me/RSS/Search?searchstr=%E5%A5%A5%E7%89%B9%E6%9B%BC`
番剧页面RSS`https://mikanani.me/RSS/Bangumi?bangumiId=2334`
无法代理，希望开发者可以增加对两个的代理支持。

个人账号订阅代理的RSS发现代理后的种子文件是这样的结构：
`http(s)://<服务器的暴露 IP/域名>/?token=<user_token>&link=https://mikanani.me/Download/20230716/24e5519e520f7efbde218c73be69c31042f37ca2.torrent`
![image](https://github.com/JeffersonQin/mikanani-proxy/assets/92703641/91e04797-5ad8-4f4f-8f67-354ad3605aae)

把`https://mikanani.me/Download/20230716/24e5519e520f7efbde218c73be69c31042f37ca2.torrent`修改为上面所说两种RSS地址后也可以打开，但是种子文件的下载地址还是未代理的，所以还是无法正常下载。
![image](https://github.com/JeffersonQin/mikanani-proxy/assets/92703641/5792f85b-9de4-49f0-9031-4a9c5bafe474)

**Comment by JeffersonQin** [comment]
因为我其实写这个项目的初衷只是为了让 BT 下载器的 RSS 能够被代理。如果需要普通的代理建议去用 clash 之类的工具。

**Comment by LinxHex** [comment]
> 因为我其实写这个项目的初衷只是为了让 BT 下载器的 RSS 能够被代理。如果需要普通的代理建议去用 clash 之类的工具。

我已经修改代码实现需求了，感谢你的开发。

**Comment by JeffersonQin** [comment]
看了你的代码终于理解你的意思了，第一次知道原来 mikan 还有这个功能 🤣

我 Pin 一下这个 Issue 以便让更多人看到

**Comment by LinxHex** [comment]
> 看了你的代码终于理解你的意思了，第一次知道原来 mikan 还有这个功能 🤣
> 
> 我 Pin 一下这个 Issue 以便让更多人看到

🤦‍♂️啊这，再一次为我拙劣的表达能力感到伤心（好一股翻译腔XD

**Comment by JeffersonQin** [comment]
不不不，这真的是我的锅 lmao。国外待的时间也不长啊，语言模块怎么就损坏了（悲
